### ISSUE TITLE
Converted repo to a Pypi package

### ISSUE THREAD

**Issue by MLResearch42** [6chaoran/jupyter-summarytools#1]
I really like your work here but wanted to make the summarytools features a little easier to use so I packaged your repo into a Pypi library.  See here:  https://pypi.org/project/summarytools/

Users can pip install it now rather than having to clone the repo into individual project directories.  The usage changed very slightly (to **"from summarytools.summarytools import dfSummary"** rather than **"from summarytools import dfSummary"**), but it seems to work properly.

**Comment by 6chaoran** [comment]
Thanks a lot for converting this as a package!  I've added the pip installation to readme.
