### ISSUE TITLE
Contributions to summarytools

### ISSUE THREAD

**Issue by hectormz** [6chaoran/jupyter-summarytools#2]
Hi @6chaoran ,
I love the original R package, and would have looked into making my own package if I didn't find it online.

How is this repo connected to the Pypi package that @Buckeyes2019 put up? Would you be interesting in making this repo a package that gets pushed to Pypi? I couldn't find it in a fork from @Buckeyes2019.

If `from summarytools.summarytools import dfSummary` is not ideal, we can make some changes to the package structure to get `from summarytools import dfSummary`. Let me know if you're open to any of changes or contributions, or I can make something similar on my own.

Thanks again for the port!

**Comment by MLResearch42** [comment]
Feel free to update (or recreate) the PyPi package the proper way. Happy to add you as editor on PyPi if that is possible. I used Poetry to create that package and had some difficulty with the file structure.

 If you do recreate it, please let me know and I will delete the existing package.

**Comment by 6chaoran** [comment]
Hi @hectormz, thanks for your interest. I'm open to changes or contributions.  If you are going to improve the package, just hope it supports python 3.6+ (as f-string is used, python3.6 is the minimal requirement). Current package has a dependency of python 3.8+, which may be not necessary.

**Comment by hectormz** [comment]
Thanks @6chaoran and @Buckeyes2019 ! I'll work on a PR to package it, and will coordinate with both about best way to publish the final package.

**Comment by MLResearch42** [comment]
@6chaoran @hectormz:  I just updated the PyPi package to drop the Python requirement down to 3.6 or higher.  I tested different directory configurations to try to eliminate the need to use "from summarytools.summarytools...." but couldn't get any alternatives to work.  I reverted it back to that format and it works properly.

**Comment by hectormz** [comment]
Hi @NIU-DSIC-AJ Sorry, I got sidelined on this. But I'll try to make the changes I think will work to fix the import and show you the branch/open a PR here.

**Comment by hectormz** [comment]
Here's a work in progress that pretty much converts the project as-is to a package: https://github.com/hectormz/jupyter-summarytools/tree/fix-package

Since there aren't a lot of dependencies (and it's pure python), it might be easiest to just use `flit` or `setuptools`, instead of `poetry`.

It also might be worth removing the entry on Pypi and re-adding it by @6chaoran to fix the many version numbers that were a result of uploading to PyPI.

There is a https://test.pypi.org/ site where you can test things instead of uploading to the official site.

**Comment by MLResearch42** [comment]
@6chaoran Ok should I delete the library from PyPi now?  @hectormz Once I pull it down, will you upload the new one to PyPi?

**Comment by hectormz** [comment]
@NIU-DSIC-AJ I think we can wait a little bit and coordinate it all (next week for me). We can make sure we have any packaging changed set and merged in the repo, before updating pypi

**Comment by 6chaoran** [comment]
@Buckeyes2019 can you add me as maintainer to the pypi? This package is broken with latest pandas, I want to upload a new version. My username is 6chaoran.

**Comment by MLResearch42** [comment]
> @Buckeyes2019 can you add me as maintainer to the pypi? This package is broken with latest pandas, I want to upload a new version. My username is 6chaoran.

Alright I just invited you to be owner on the package.  Feel free to change/edit anything you want (or just delete the whole thing and start a new package).

**Comment by 6chaoran** [comment]
I updated the package to compatible with recent pandas. (1.4+) and re-uploaded to pypi. I used setuptools and able to import dfSummary from summarytools directly.
