### ISSUE TITLE
does not work in google colab

### ISSUE THREAD

**Issue by caroheymes** [6chaoran/jupyter-summarytools#3]
Sorry that your module does not work in google colab
`ImportError: cannot import name 'FilePath' from 'pandas._typing' (/usr/local/lib/python3.8/dist-packages/pandas/_typing.py)`
pandas version : pandas-1.5.3

**Comment by 6chaoran** [comment]
Thanks for trying out in colab. 
Did you restart your colab terminal after installing new package ?
I managed to make it work under following setting.

![image](https://user-images.githubusercontent.com/10956124/217789153-8a51025f-88e4-4e12-9894-f273a10c965b.png)

**Comment by NnamdiOdozi** [comment]
@6chaoran Do you also need to run  !pip install summarytools since it does not appear to come as a default in Colab.

I get this error when I pass a 5 col dataframe to dfSummary:

<img width="514" alt="image" src="https://user-images.githubusercontent.com/21362863/219043952-4a4e34c1-7aaa-4fe1-ac56-e2bee4468288.png">

**Comment by NnamdiOdozi** [comment]
This is my dataframe that I'm passing:

<img width="391" alt="image" src="https://user-images.githubusercontent.com/21362863/219044402-bc1e559c-a3c1-498e-917c-3b99b57d5968.png">

And this is my setup:

<img width="463" alt="image" src="https://user-images.githubusercontent.com/21362863/219044557-a2e1f0de-e350-4dda-9c11-3c57686422c7.png">

**Comment by 6chaoran** [comment]
Hi @NnamdiOdozi, the error suggest incompatible version of matplotlib, can you reinstall matplotlib using !pip install matplotlib==3.1.3 and restart your colab terminal to retry. Yes, summarytools is not preintalled by colab, you need to install by yourself.

**Comment by NnamdiOdozi** [comment]
Thanks Chaoran. Tried it and it worked. I also needed to reinstall jinja2

<img width="302" alt="image" src="https://user-images.githubusercontent.com/21362863/219651196-e833798e-6b25-42bd-b528-c7531d39b342.png">



<img width="837" alt="image" src="https://user-images.githubusercontent.com/21362863/219651081-262f3381-9058-4c27-91cb-86d6a918477f.png">

**Comment by caroheymes** [comment]
Thanks ! I did not see your feedback and apologize for the delay
INSTALLS : 
!pip install Jinja2==3.1.2
!pip install matplotlib==3.1.3
!pip install jupyter-summarytools


but images do not appear...
![image](https://user-images.githubusercontent.com/32369680/221948028-dba75b8b-3424-47ec-8e35-869a0392028d.png)
