### ISSUE TITLE
Incorrect summary (column names do not match the contents)

### ISSUE THREAD

**Issue by GegznaV** [6chaoran/jupyter-summarytools#4]
Consider the following code:

```python
import pandas as pd
from summarytools import dfSummary

url = 'https://people.sc.fsu.edu/~jburkardt/data/csv/hw_200.csv'
df2 = pd.read_csv(url)
print(df2.head())

dfSummary(df2)

df2.mean()
```

Column names and summaries are mixed between several rows.

In this example, column 3 has no summaries:

![image](https://user-images.githubusercontent.com/12725868/232167848-61d4aff4-4310-4cb5-96aa-b2ee98f3adc5.png)

And here it is visible that at least the mean is shown for the wrong variable:

![image](https://user-images.githubusercontent.com/12725868/232168159-5e9a7f22-a475-44ac-8617-75a9c1a1c806.png)

Can this be fixed?

**Comment by 6chaoran** [comment]
Hi @GegznaV, thanks for your interest to this package. 
I need to know the version of `summarytools` and which environment you are working on for me to reproduce your error.

From my side, I tested the latest version 0.2.3 on Colab and it works fine for me.  Do you want to double check your setup?

![image](https://user-images.githubusercontent.com/10956124/232177821-0ba367dd-c429-4683-8415-2b5eea080e0e.png)

**Comment by GegznaV** [comment]
I use VSCode on Windows 10 and Python 3.11.3.

![image](https://user-images.githubusercontent.com/12725868/232340335-6552342b-3544-426b-8642-569a4105fa26.png)


And this is the newest version that `pip` downloads:

```
$ pip install jupyter-summarytools
Requirement already satisfied: jupyter-summarytools in c:\users\user\anaconda3\envs\py311\lib\site-packages (0.2.1)
```

**Comment by 6chaoran** [comment]
Hi @GegznaV, 
I uploaded the 0.2.3 version to `jupyter-summarytools` as well. You can run `pip install -U  jupyter-summarytools`  or `pip install summarytools` to get the latest version.  Sorry for some confusion and I will fix the installation guide in the README.md. 
Let me know if you still have some errors.
