### ISSUE TITLE
Broken link in PyPi to examples

### ISSUE THREAD

**Issue by GegznaV** [6chaoran/jupyter-summarytools#5]
![image](https://user-images.githubusercontent.com/12725868/232340732-f60137ad-8f7a-4c08-a99b-f2191377986f.png)

![image](https://user-images.githubusercontent.com/12725868/232340664-6fe05165-637f-47e5-9002-d8b115b29b23.png)

**Comment by 6chaoran** [comment]
The link should point to here https://github.com/6chaoran/jupyter-summarytools/blob/master/quick-start.ipynb
I will fix it at the next package release.
