### ISSUE TITLE
Feature Request: Provide ability to write directly to an html file

### ISSUE THREAD

**Issue by gdevenyi** [6chaoran/jupyter-summarytools#6]
I'd like to generate a automated summary of dataframe I can load and look at later, rather than interactively in a Jupyter notebook.

**Comment by 6chaoran** [comment]
Thanks @gdevenyi for your interest and suggestions. You can actually do it with the following code to save it as HTML.

```python
from summarytools import dfSummary
import pandas as pd

data = pd.read_csv(csv_file_path)
res = dfSummary(data)
res.to_html('my_data_summary.html')
```
