### ISSUE TITLE
Consider adding to a channel?

### ISSUE THREAD

**Issue by eotf** [6chaoran/jupyter-summarytools#7]
Just wondering why you have decided not to.

**Comment by 6chaoran** [comment]
> Just wondering why you have decided not to.

Could you elaborate on the channel part? What's the benefit of adding to a channel?

**Comment by eotf** [comment]
A channel like conda-forge so people can directly install from their environments instead of cloning the repo.

**Comment by 6chaoran** [comment]
Hmmm, you actually can simply run 'pip install summarytools' for installation. 

You can refer the README for updated documentation
